wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720612331
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.12
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 96
learning_rate:
  desc: null
  value: 0.01
n_epochs:
  desc: null
  value: 20
n_steps:
  desc: null
  value: 2048
